parameters:
    stageName: ''
    stageDisplayName: ''
    condition: ''
    dependsOn: ''
    poolname: ''
    envName: ''
    envGroup: ''
    variableFilePath: ''

stages:
- stage: ${{parameters.stageName}}
  displayName: ${{parameters.stageDisplayName}}
  dependsOn: ${{parameters.dependsOn}}
  condition: ${{parameters.condition}}

  jobs:

  - deployment: Deploy
    displayName: ${{parameters.envName}}_Deployment
    pool:
      name: ${{parameters.poolname}}
    variables:
      - template: ${{parameters.variableFilePath}}
    environment: '${{parameters.envGroup}}'
  #checkout: self    #Can be Enabled to add repository as an artifact
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - checkout: self

          - task: CheckRemedyStatusDeploying@3
            inputs:
              CRQ: '$(CRQ)'
            condition: eq('${{parameters.envName}}', 'PROD')

          - task: AzureFunctionApp@1
            displayName: Azure Function App Deploy
            inputs:
              azureSubscription: '${{variables.azureSubscription}}'
              appType: functionApp
              appName: '${{variables.appName}}'
              package: $(Agent.BuildDirectory)/**/*.zip
              appSettings: '-FUNCTIONS_WORKER_RUNTIME dotnet -FUNCTIONS_EXTENSION_VERSION ~4 -StiboVIM_ServiceBusSubscription "EnterpriseVendorData" -ContainerName "raw" -StiboVIM_ServiceBusTopic ${{variables.ServiceBusTopic}} -AccountName ${{variables.AccountName}} -ServiceBusURL ${{variables.ServiceBusURL}} -StiboVIM_DirectoryPath "data/Vendor/StiboVIM/landing" -DeadLetterQueuePath "/$DeadLetterQueue"'
