###############################################################################
#                                   PROD VARIABLES                            #
# Only include non Secure variables and for secure variables add it in Pipeline
# with 'secrets' enabled
###############################################################################

variables:

    azureSubscription: 'Azure DevOps - Enterprise Data Production'
    appName: 'fa-ea2-edaa-vim-integration'
#AppSetting Variables
    ServiceBusTopic: 'topic-vim-integration'
    ServiceBusURL: 'Endpoint=sb://sb-ea2-merch.servicebus.windows.net/;Authentication=ManagedIdentity'
    AccountName: 'saea2ragrsedaadatalake'
